// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaDH_S2mIOgPxgQG0hLptVo3dXp-xzPgQ',
    appId: '1:675312002140:web:5bb0f8fa6018a6676ef299',
    messagingSenderId: '675312002140',
    projectId: 'project-one-fgeund',
    authDomain: 'project-one-fgeund.firebaseapp.com',
    storageBucket: 'project-one-fgeund.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjLoYiCwV32tgP7BTE6nirKoPAmaCStFM',
    appId: '1:675312002140:android:ed8231b03967a5146ef299',
    messagingSenderId: '675312002140',
    projectId: 'project-one-fgeund',
    storageBucket: 'project-one-fgeund.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzWrkdSDIfg7KVt-s8dKFYcIEiHVaKuvY',
    appId: '1:675312002140:ios:8e4f0d6bdc3505486ef299',
    messagingSenderId: '675312002140',
    projectId: 'project-one-fgeund',
    storageBucket: 'project-one-fgeund.firebasestorage.app',
    iosClientId: '675312002140-aceats7ammuoa4l76kgo5f8vord7qd6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
